baseURL = 'https://openeverest.io/'
languageCode = 'en-us'
title = 'Everest Open Source'

[params]
  description = 'Website for Everest Open Source project'
  author = 'Everest Team'

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"