baseURL = 'https://openeverest.io/'
languageCode = 'en-us'
title = 'OpenEverest'
staticDir = ['static', 'assets']

[params]
  tagline = 'Open-Source Database Platform'
  description = 'OpenEverest is an open-source platform for automated database provisioning and management. It supports multiple database technologies and can be hosted on any Kubernetes infrastructure, in the cloud or on-premises.'
  author = 'OpenEverest Team'
  defaultSocialImage = '/images/brandkit/hero-image-2x1-ratio.png'
  apiSpecURL = 'https://raw.githubusercontent.com/percona/everest/refs/tags/v${version}/docs/spec/openapi.yml'
  defaultApiVersion = '1.13.0'

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"