baseURL = '/'
languageCode = 'en-us'
title = 'Everest Open Source'
theme = ''

[params]
  description = 'Website for Everest Open Source project'
  author = 'Everest Team'

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
