baseURL = 'https://openeverest.io/'
languageCode = 'en-us'
title = 'OpenEverest'
staticDir = ['static', 'assets']

[params]
  description = 'Website for OpenEverest project'
  author = 'OpenEverest Team'

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"